spring:
  datasource:
      url: jdbc:mysql://localhost:3306/example?serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: 111111
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
   mapperLocations: classpath:/mapper/*.xml
